# Generated by Django 4.2.2 on 2024-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
