# Generated by Django 4.2.2 on 2024-07-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='num_songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='speechiness',
        ),
    ]
