# Generated by Django 4.2.2 on 2024-07-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
        migrations.AddField(
            model_name='song',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.song'),
        ),
    ]
