# Generated by Django 4.2.2 on 2024-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rating_remove_song_rating_song_star_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
