# Generated by Django 4.2.2 on 2024-07-17 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0010_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='song',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'title')},
        ),
    ]
