# Generated by Django 4.2.2 on 2024-07-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_rename_title_rating_song_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
